management:
  endpoint:
    health:
      show-details: always
  server:
    port: 8080

spring:
  application:
    name: ms-bantads-manager
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:bantads}
    password: ${DB_PASS:secret}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bantads}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false